sudo: false
language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  # Fail early since some targets take awhile to complete.
  - make clean && make dummy && make linkcheck && make preview
  - flake8
